
#!/usr/bin/env python3
r"""
chain_method_c.py -- adaptive verifier/solver chaining for method_c.

method_c's verifier is a *solution checker*, not a *can-I-solve-this*
predictor like method_a's: it is shown the problem plus a candidate solution
(generated by the method_ac solver) and asked "is this solution correct?"
(see pipeline/tasks/{task}/templates/method_c_predictors_rl/eval.txt -- the
prompt has a `{solution}` slot, not a `{hint_sequence}` one; the hint the
solver saw is baked into the candidate text, never shown to the verifier
directly).

That makes method_c's chaining loop different from method_a's in one
important way: because the *verifier's input at every round is a solver
output*, the solver has to run once per round too, not just once at the end.
Each round:

    Round 0 (no hints): solver generates a candidate solution to the bare
        problem. Verifier is shown (problem, that candidate) and outputs
        <answer>1</answer> (accept) or <answer>0</answer> (reject).
        Accepted -> rollout is done; that round's solver candidate is its
        final answer.
        Rejected -> add one hint and carry the rollout into round 1.
    Round 1 (1 hint): solver generates a *new* candidate solution, now
        conditioned on 1 hint. Verifier re-checks that new candidate. Same
        accept/continue split as round 0.
    ...continues until a round is accepted, or the rollout is rejected even
    at its own last possible round -- every available hint shown, nothing
    left to escalate to (each problem can have a different number of
    available hints, so rollouts drop out of the loop at different rounds).
    In that last case, the solver candidate *from that same, rejected final
    round* becomes the rollout's final answer anyway (there's nowhere else
    to go) -- no extra, unverified solver call is needed, since the verifier
    was already run at that final round.

Because the solver has to keep generating throughout the loop (not just at
the very end, as in chain_method_a.py), the solver and verifier models are
both loaded and kept resident for the whole run, rather than loading one,
running it to completion, then swapping to the other. Size
--solver-gpu-memory-utilization / --verifier-gpu-memory-utilization (they
must sum to well under 1.0) accordingly.

Each round hands vLLM the whole round's prompt list in one call and lets it
do its own continuous batching/scheduling (sync `Generator.generate`, or
`AsyncGenerator.generate_async` with `--async`) -- there's no manual
--batch-size chunking.

Progress is checkpointed to `<output>.checkpoint.json` after every round, so
a crash (or Ctrl-C) doesn't have to redo already-decided rounds -- rerunning
the same command picks up from the last completed round. The checkpoint is
removed once the run finishes and the real output is written.

method_a's and method_c's fixed-hint solver is always the shared "method_ac"
generator/template -- only the verifier differs between the two methods (see
chain_method_a.py for the method_a verifier, which checks "can you solve this
given the hints so far?" instead of checking a candidate solution).

Usage:
    MODEL="qwen3-4b-base"
    TASK="competition_math"

    CUDA_VISIBLE_DEVICES=2 python chain_method_c.py \
        --task "${TASK}" \
        --eval-dataset artifacts/${TASK}/problems/eval.json \
        --verifier-model artifacts/${TASK}/models/method_c_models/${MODEL}/model \
        --solver-model artifacts/${TASK}/models/method_ac_models/${MODEL}/model \
        --num-samples 1 \
        --max-hints 5 \
        --async \
        --output artifacts/${TASK}/models/method_c_predictors_rl/${MODEL}/evals/eval__chained_1s.json
"""

import argparse
import gc
from datetime import datetime
from pathlib import Path

from pipeline.commands.inference import compute_hint_metrics, count_truncation, format_hint_metrics
from pipeline.core.generator import AsyncGenerator, Generator, GenerationConfig
from pipeline.core.io import load_json, save_json
from pipeline.core.method import Method
from pipeline.core.utils import extract_answer
from pipeline.tasks import get_task

# The fixed-hint solver template/model group is shared by method_a and
# method_c -- only the verifier differs. Hardcoded rather than a CLI flag so
# the two chain_method_*.py scripts can't accidentally point at mismatched
# solver conventions.
SOLVER_METHOD_NAME = "method_ac"
VERIFIER_METHOD_NAME = "method_c"


def get_hints_list(primitive: dict) -> list[str]:
    """Available hints for a primitive, countdown or competition_math.

    Mirrors pipeline/commands/data.py's extraction exactly: countdown carries
    a flat `hint_exprs` list (each entry already the full cumulative partial
    expression up to that point); competition_math carries a `prefix_hints`
    dict of up to 6 standalone steps (`hint_1`..`hint_6`).
    """
    hints_list = list(primitive.get("hint_exprs", []))
    if not hints_list:
        prefix_hints = primitive.get("prefix_hints", {})
        for i in range(1, 7):
            key = f"hint_{i}"
            if key in prefix_hints:
                hints_list.append(prefix_hints[key])
    return hints_list


def hint_sequence_for_level(task_name: str, hints_list: list[str], level: int) -> str:
    """Render the `{hint_sequence}` placeholder text for a given hint level.

    Matches pipeline/commands/data.py exactly. Level 0 has no partial
    solution. competition_math's hints are independent steps, so the partial
    solution is every step up to `level` concatenated; countdown's hint_exprs
    are each already the full cumulative expression, so only the single entry
    at `level` is shown.
    """
    if level == 0:
        return "No partial solution"
    if task_name == "competition_math":
        return "\n".join(hints_list[:level])
    return hints_list[level - 1]


class RoundGenerator:
    """One loaded model, generating across one or more rounds -- sync or async.

    vLLM's LLM.generate() (sync) and AsyncLLMEngine (async, via
    AsyncGenerator.generate_async) both already do their own continuous
    batching over whatever prompt list they're handed, so `.run()` always
    submits a full round in one call rather than chunking it into a
    --batch-size.

    In async mode, a single event loop is created lazily on the first `.run()`
    call and reused for every subsequent round on this instance, rather than
    calling `asyncio.run()` fresh each time. AsyncLLMEngine spawns its
    background output-handler task bound to whichever loop is running when the
    engine is first touched; calling `asyncio.run()` again for round 2 tears
    down that loop and starts a brand new one, orphaning the engine's
    background task -- the next `engine.generate()` call then dies with
    `EngineDeadError` ("EngineCore proc ... died unexpectedly"). Reusing one
    loop for the engine's whole lifetime (mirrored by closing it in
    `.close()`) avoids that. Solver and verifier each get their own
    RoundGenerator (and so their own loop), since both stay resident at once.
    """

    def __init__(self, config: GenerationConfig, use_async: bool):
        self.use_async = use_async
        self._gen = AsyncGenerator(config) if use_async else Generator(config)
        self._loop = None

    def run(self, prompts: list[list[dict]]) -> list[list[dict]]:
        if not prompts:
            return []
        if self.use_async:
            if self._loop is None:
                import asyncio
                self._loop = asyncio.new_event_loop()
            return self._loop.run_until_complete(self._gen.generate_async(prompts, num_samples=1))
        return self._gen.generate(prompts)

    def close(self) -> None:
        """Release the loaded model and free its GPU memory."""
        if self.use_async:
            if self._loop is not None:
                self._loop.run_until_complete(self._async_close())
                self._loop.close()
                self._loop = None
            else:
                self._gen.close()
        else:
            self._gen._model = None
        del self._gen
        gc.collect()
        import torch
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    async def _async_close(self) -> None:
        # AsyncGenerator.close() is sync, but engine.shutdown() underneath
        # tears down asyncio background tasks -- run it while our own loop
        # (the one those tasks are bound to) is still alive and running.
        self._gen.close()


class ChainItem:
    """One (source_index, trial) rollout as it moves through solver+verifier
    rounds. Unlike chain_method_a.py's ChainItem, `final_sample` holds the
    actual solver generation that becomes this rollout's answer -- since
    here the solver runs every round, not just once at the very end.
    """

    __slots__ = (
        "source_index", "trial", "primitive", "ground_truth", "hints_list",
        "local_max_hints", "resolved", "forced", "selected_level", "trace",
        "final_sample",
    )

    def __init__(self, source_index, trial, primitive, ground_truth, hints_list, local_max_hints):
        self.source_index = source_index
        self.trial = trial
        self.primitive = primitive
        self.ground_truth = ground_truth
        self.hints_list = hints_list
        self.local_max_hints = local_max_hints
        self.resolved = False
        # Set alongside `resolved` once a decision is made: True only when
        # the verifier rejected every hint level, including local_max_hints
        # (the last one it's ever queried at) -- run_chain_rounds reuses that
        # final round's solver candidate as final_sample rather than issuing
        # another, unverified solver call.
        self.forced = False
        # Fallback if the verifier never accepts: use every hint this
        # problem has. Overwritten the moment a round's verifier accepts.
        self.selected_level = local_max_hints
        self.trace = []
        # The solver generation dict ({"text", "finish_reason", "token_count"})
        # that became this rollout's final answer -- either the accepted
        # round's candidate, or the forced final-level candidate.
        self.final_sample = None


def build_items(task, primitives: list[dict], num_samples: int, max_hints: int) -> list[ChainItem]:
    items = []
    for primitive in primitives:
        hints_list = get_hints_list(primitive)
        local_max_hints = min(max_hints, len(hints_list))
        ground_truth = task.get_ground_truth(primitive)
        for t in range(num_samples):
            items.append(ChainItem(
                source_index=primitive["index"],
                trial=t,
                primitive=primitive,
                ground_truth=ground_truth,
                hints_list=hints_list,
                local_max_hints=local_max_hints,
            ))
    return items


# =============================================================================
# Checkpointing -- round-by-round progress, so a crash mid-run doesn't have to
# redo already-decided rounds. Both the solver candidate and the verifier's
# verdict for it are checkpointed every round, since method_c's solver runs
# every round (not just once, as in chain_method_a.py).
# =============================================================================

def checkpoint_path_for(output_path: Path) -> Path:
    return output_path.with_name(f"{output_path.stem}.checkpoint.json")


def save_checkpoint(path: Path, items: list[ChainItem]) -> None:
    data = [
        {
            "source_index": it.source_index,
            "trial": it.trial,
            "resolved": it.resolved,
            "forced": it.forced,
            "selected_level": it.selected_level,
            "trace": it.trace,
            "final_sample": it.final_sample,
        }
        for it in items
    ]
    save_json(path, data)


def restore_from_checkpoint(items: list[ChainItem], checkpoint_data: list[dict]) -> int:
    by_key = {(d["source_index"], d["trial"]): d for d in checkpoint_data}
    restored = 0
    for it in items:
        d = by_key.get((it.source_index, it.trial))
        if d is None:
            continue
        it.resolved = d["resolved"]
        it.forced = d.get("forced", False)
        it.selected_level = d["selected_level"]
        it.trace = d["trace"]
        it.final_sample = d.get("final_sample")
        restored += 1
    return restored


def run_chain_rounds(
    task,
    task_name: str,
    solver: RoundGenerator,
    verifier: RoundGenerator,
    solver_template: str,
    verifier_template: str,
    items: list[ChainItem],
    checkpoint_path: Path,
) -> None:
    """Adaptively resolve every item via live solver+verifier rounds.

    Round `level` only includes items that are still unresolved, have not yet
    gone past their own hint budget (local_max_hints >= level -- note the
    solver+verifier ARE run at level == local_max_hints, the "every available
    hint shown" level, since there's still a real accept/reject decision to
    make there; it's simply the last round an item can ever be escalated
    past), and -- so a resumed run doesn't repeat rounds a previous run
    already decided -- whose trace shows this is exactly their next round
    (len(trace) == level).

    Unlike chain_method_a.py's run_verifier_rounds, each round here generates
    a *new* solver candidate (conditioned on that round's hint level) and
    immediately checks it with the verifier, since method_c's verifier input
    is a solution, not just a hint sequence.
    """
    max_level = max((it.local_max_hints for it in items), default=0)

    for level in range(max_level + 1):
        round_items = [
            it for it in items
            if not it.resolved and it.local_max_hints >= level and len(it.trace) == level
        ]
        if not round_items:
            continue

        solver_prompts = []
        for it in round_items:
            hint_seq = hint_sequence_for_level(task_name, it.hints_list, level)
            rendered = solver_template.replace("{hint_sequence}", hint_seq)
            solver_prompts.append(task.format_prompt(it.primitive, rendered, include_assistant_prefix=True))

        print(f"[solver] round {level}: {len(solver_prompts)} prompts "
              f"({sum(1 for i in items if i.resolved)} resolved so far)")
        solver_results = solver.run(solver_prompts)

        verifier_prompts = []
        for it, samples in zip(round_items, solver_results):
            candidate_text = samples[0]["text"]
            rendered = verifier_template.replace("{solution}", candidate_text)
            # method_c's verifier reasons in <think>...</think> before
            # answering, so (unlike method_a's) its prompt includes the
            # assistant prefix to prompt that reasoning.
            verifier_prompts.append(task.format_prompt(it.primitive, rendered, include_assistant_prefix=True))

        print(f"[verifier] round {level}: {len(verifier_prompts)} prompts")
        verifier_results = verifier.run(verifier_prompts)

        n_unparseable = 0
        for it, solver_sample, verifier_sample in zip(round_items, solver_results, verifier_results):
            solver_gen = solver_sample[0]
            verifier_gen = verifier_sample[0]
            verifier_text = verifier_gen["text"]
            answer = extract_answer(verifier_text)
            if answer not in ("0", "1"):
                # Malformed verifier output -- treat like a "0": add a hint
                # and keep going rather than aborting a long run over one bad
                # sample.
                n_unparseable += 1
                prediction = 0
            else:
                prediction = int(answer)
            it.trace.append({
                "hint_level": level,
                "solver_generation": solver_gen["text"],
                "solver_finish_reason": solver_gen.get("finish_reason", "unknown"),
                "solver_token_count": solver_gen.get("token_count", 0),
                "verifier_generation": verifier_text,
                "verifier_prediction": prediction,
            })
            if prediction == 1:
                it.resolved = True
                it.selected_level = level
                it.final_sample = solver_gen

        if n_unparseable:
            print(f"[verifier] round {level}: {n_unparseable}/{len(round_items)} "
                  f"outputs were not <answer>0/1</answer>; counted as 0")

        save_checkpoint(checkpoint_path, items)

    # Anything still unresolved was rejected by the verifier even at its own
    # last available hint level (level == local_max_hints, just run above) --
    # there's nowhere further to escalate to, so it's forced to
    # local_max_hints (already the __init__ default) despite the rejection.
    # That round already produced a solver candidate for it (in trace[-1]),
    # so no extra unverified solver call is needed -- just reuse it.
    n_forced = 0
    for it in items:
        if not it.resolved:
            it.resolved = True
            it.forced = True
            last = it.trace[-1]
            it.final_sample = {
                "text": last["solver_generation"],
                "finish_reason": last["solver_finish_reason"],
                "token_count": last["solver_token_count"],
            }
            n_forced += 1
    if n_forced:
        print(f"[verifier] {n_forced} rollouts were rejected at every hint level, "
              f"including their max, and are forced to their max hint level "
              f"(reusing that round's solver candidate)")
    save_checkpoint(checkpoint_path, items)


def build_details(task, items: list[ChainItem]) -> list[dict]:
    details = []
    for it in items:
        gen = it.final_sample
        primitive_for_check = {"index": it.source_index, **it.ground_truth}
        is_correct, meta = task.check_correctness(primitive_for_check, gen["text"])

        detail = {
            "index": it.source_index,
            "source_index": it.source_index,
            "trial_index": it.trial,
            "variant": it.ground_truth.get("variant", "unknown"),
            "level": it.ground_truth.get("level", "unknown"),
            "ground_truth": it.ground_truth,
            "num_hints": it.selected_level,
            "selected_hint_level": it.selected_level,
            "forced_at_max_hints": it.forced,
            "correct": is_correct,
            "generation": gen["text"],
            "predicted_answer": meta.get("predicted_answer"),
            "error": meta.get("error"),
            "finish_reason": gen.get("finish_reason", "unknown"),
            "token_count": gen.get("token_count", 0),
            "chain_trace": it.trace,
        }
        details.append(detail)
    return details


def build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--task", required=True, help="Task name (countdown, competition_math)")
    p.add_argument("--eval-dataset", required=True, type=Path,
        help="Path to the raw eval partition (artifacts/{task}/problems/eval.json)")
    p.add_argument("--verifier-model", required=True, help="Verifier (method_c) model path")
    p.add_argument("--solver-model", required=True, help="Solver (method_ac) model path")
    p.add_argument("--output", required=True, type=Path, help="Output path for combined results")
    p.add_argument("--num-samples", type=int, default=1,
        help="Independent rollouts per problem (default: 1)")
    p.add_argument("--max-hints", type=int, default=5,
        help="Cap on hint rounds; a problem with fewer available hints stops sooner (default: 5)")
    p.add_argument("--async", dest="use_async", action="store_true",
        help="Use vLLM's AsyncLLMEngine instead of the sync engine (optimal throughput; "
             "required for --data-parallel-size > 1)")
    p.add_argument("--solver-tensor-parallel-size", type=int, default=1)
    p.add_argument("--solver-data-parallel-size", type=int, default=1,
        help="Independent solver model replicas, prompts sharded across them. Requires --async.")
    p.add_argument("--solver-gpu-memory-utilization", type=float, default=0.45,
        help="Solver and verifier are both resident at once -- default splits the GPU 0.45/0.45")
    p.add_argument("--verifier-tensor-parallel-size", type=int, default=1)
    p.add_argument("--verifier-data-parallel-size", type=int, default=1,
        help="Independent verifier model replicas, prompts sharded across them. Requires --async.")
    p.add_argument("--verifier-gpu-memory-utilization", type=float, default=0.45,
        help="Solver and verifier are both resident at once -- default splits the GPU 0.45/0.45")
    p.add_argument("--seed", type=int, default=42, help="Random seed for generation")
    p.add_argument("--verifier-max-new-tokens", type=int, default=1024,
        help="method_c's verifier reasons in <think>...</think> before <answer>0/1</answer>, "
             "unlike method_a's direct answer (default: 1024)")
    p.add_argument("--verifier-temperature", type=float, default=1.0)
    p.add_argument("--verifier-top-p", type=float, default=1.0)
    p.add_argument("--solver-max-new-tokens", type=int, default=2048)
    p.add_argument("--solver-temperature", type=float, default=1.0)
    p.add_argument("--solver-top-p", type=float, default=1.0)
    p.add_argument("--verbose", action="store_true", help="Print sample prompts during generation")
    return p


def main():
    args = build_arg_parser().parse_args()

    task = get_task(args.task)
    verifier_method = Method.load(VERIFIER_METHOD_NAME, args.task)
    solver_method = Method.load(SOLVER_METHOD_NAME, args.task)
    verifier_template = verifier_method.load_template(args.task, "eval")
    solver_template = solver_method.load_template(args.task, "eval")

    primitives = load_json(args.eval_dataset)
    print(f"Loaded {len(primitives)} primitives from {args.eval_dataset}")

    items = build_items(task, primitives, args.num_samples, args.max_hints)
    print(f"{len(items)} total rollouts ({len(primitives)} problems x {args.num_samples} samples)")

    checkpoint_path = checkpoint_path_for(args.output)
    if checkpoint_path.exists():
        restored = restore_from_checkpoint(items, load_json(checkpoint_path))
        print(f"Resuming from checkpoint {checkpoint_path}: {restored} rollouts restored "
              f"({sum(1 for it in items if it.resolved)} already resolved)")

    solver_config = GenerationConfig(
        model_name=args.solver_model,
        max_new_tokens=args.solver_max_new_tokens,
        temperature=args.solver_temperature,
        top_p=args.solver_top_p,
        num_samples=1,  # each rollout `t` is already one independent sample
        tensor_parallel_size=args.solver_tensor_parallel_size,
        data_parallel_size=args.solver_data_parallel_size,
        gpu_memory_utilization=args.solver_gpu_memory_utilization,
        verbose=args.verbose,
        seed=args.seed,
    )
    verifier_config = GenerationConfig(
        model_name=args.verifier_model,
        max_new_tokens=args.verifier_max_new_tokens,
        temperature=args.verifier_temperature,
        top_p=args.verifier_top_p,
        num_samples=1,
        tensor_parallel_size=args.verifier_tensor_parallel_size,
        data_parallel_size=args.verifier_data_parallel_size,
        gpu_memory_utilization=args.verifier_gpu_memory_utilization,
        verbose=args.verbose,
        seed=args.seed,
    )

    # Both models stay resident for the whole run: method_c's verifier checks
    # a solver-generated candidate, so the solver has to run every round, not
    # just once at the end like chain_method_a.py.
    solver = RoundGenerator(solver_config, args.use_async)
    verifier = RoundGenerator(verifier_config, args.use_async)

    run_chain_rounds(
        task, args.task, solver, verifier, solver_template, verifier_template, items, checkpoint_path,
    )

    solver.close()
    verifier.close()

    details = build_details(task, items)

    metrics = task.compute_metrics(details)
    metrics["truncation"] = count_truncation(details)
    hint_metrics = compute_hint_metrics(details)

    results = {
        "verifier_model": args.verifier_model,
        "solver_model": args.solver_model,
        "eval_dataset": str(args.eval_dataset),
        "timestamp": datetime.now().isoformat(),
        "config": {
            "num_samples": args.num_samples,
            "max_hints": args.max_hints,
            "verifier": {
                "max_new_tokens": args.verifier_max_new_tokens,
                "temperature": args.verifier_temperature,
                "top_p": args.verifier_top_p,
            },
            "solver": {
                "max_new_tokens": args.solver_max_new_tokens,
                "temperature": args.solver_temperature,
                "top_p": args.solver_top_p,
            },
        },
        "metrics": metrics,
        "details": details,
        "hint_metrics": hint_metrics,
    }

    print(task.format_metrics(metrics, "method_c_chain"))
    print(format_hint_metrics(hint_metrics, details))

    save_json(args.output, results)
    print(f"\nSaved chained evaluation to {args.output}")

    # The run finished cleanly -- the checkpoint has served its purpose.
    checkpoint_path.unlink(missing_ok=True)

    return args.output


if __name__ == "__main__":
    main()
